import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='container mx-auto text-white'>
          <div className="w-full flex items-center justify-center text-blue-500 gap-6 p-6">
            <Link href="/">
              Home
            </Link>
            <Link
              href="/visitors"
            >
              Visitors
            </Link>
          </div>
          <div className='flex gap-6'>
            {team}
            {analytics}
          </div>
          {children}
        </div>

      </body>
    </html>
  );
}
