import React from 'react'
import { Button } from 'antd'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Antd Nextjs Registry Test",
  description: "Generated by create next app",
};

const Test:React.FC = () => {
  return (
    <div>
        <h2>这是测试页面</h2>
        <Button type='primary'>Antd Button</Button>
    </div>
  )
}

export default Test